module.exports = {
  id: 'moving-head-beam-1',
  label: 'Moving Head Beam 200W',
  fixtureType: 'moving_head_beam',
  match: { name: 'moving head beam 1' },
  channels: {
    color:         { alias: 'color_wheel' },
    dimmer:        { alias: 'fecho_lampada' },
    strobe:        { alias: 'strobo' },
    prism:         { alias: 'prism_1' },
    prismRotation: { alias: 'prism_1_rotation' },
    gobo:          { alias: 'gobo_wheel' },
    movementSpeed: { alias: 'virtual_speed' },
    pan:           { alias: 'pan' },
    panFine:       { alias: 'pan_fine', optional: true },
    tilt:          { alias: 'tilt' },
    tiltFine:      { alias: 'tilt_fine', optional: true },
  },
  capabilities: {
    color:         { type: 'enumerated', status: 'mapping-incomplete' },
    dimmer:        { type: 'continuous', status: 'ready' },
    movementSpeed: { type: 'continuous', status: 'ready' },
    pan:           { type: 'continuous', status: 'ready' },
    tilt:          { type: 'continuous', status: 'ready' },
    strobe:        { type: 'range',      status: 'mapping-incomplete' },
    prism:         { type: 'enumerated', status: 'mapping-incomplete' },
    prismRotation: { type: 'range',      status: 'mapping-incomplete' },
    gobo:          { type: 'enumerated', status: 'mapping-incomplete' },
  },
};
